Feature/advanced calendar
mobileappdevhm19/apps4students-team-4 pull request #40
Opened 2019-06-11 15:50 UTC by Nilsilino

2019-06-11 16:48 UTC, 01Student10 commented
shouldnt you merge with the develop branch not with the master?

2019-06-12 17:05 UTC, 01Student10 requested changes

2019-06-12 17:05 UTC, 01Student10 commented on lib/presenter/settings.dart
>      final Future<List<Subject>> subjects = DBHelper().getSubjects();
you should use the dbHelper object of the Appstate instead of calling the factory DBHelper().

2019-06-13 05:41 UTC, stigito approved these changes

2019-06-13 13:45 UTC, 01Student10 approved these changes

2019-06-13 13:46 UTC, merged